### ISSUE TITLE
建议增加

### ISSUE THREAD

**Issue by xiaomosama** [lichenzero/easy_shorten_url_by_php#1]
建议增加 自定义目录名  demo.com/xxx
二维码生成
短网址还原

**Comment by lichenzero** [comment]
我会在空闲时间对这个项目进行更新。短网址还原及二维码生成是不错的建议。
自定义目录名是自定义一个短网址的吗？

**Comment by 1760714192** [comment]
自定义demo.com/xxx  中的xx字符

**Comment by lichenzero** [comment]
明白了，相当于自定义设置一个短网址。
因为原本是采用自动递增的方式，所以如果要自定义需要修改整体逻辑，所以这个只能放在其他附加功能设计完毕后再做。
